# Generated by Django 5.1.1 on 2024-11-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
